## Floyd-Warshall Transitive Closure

In [1]:
import numpy as np

In [2]:
def floyd_warshal_tc(input_matrix):
    R_0 = input_matrix
    R_k_1 = R_0
    R_k = np.zeros(input_matrix.shape)
    N = input_matrix.shape[0]
    print(f'R\u2070:\n{R_0}')
    for k in range(N):
        for i in range(N):
            for j in range(N):
                R_k[i,j] = R_k_1[i,j].astype(bool) | (R_k_1[i,k].astype(bool) & R_k_1[k,j].astype(bool))
                R_k[i,j] = R_k[i,j].astype(int)
        print(f'\nR_{k+1}:\n{R_k}')
        R_k_1 = R_k
    print(f'\nTransitive Closure T: \n {R_k}')   
    

In [4]:
floyd_warshal_tc(np.array([[0,1,0,0],[0,0,1,0],[1,0,0,1],[0,0,0,0]]))

R⁰:
[[0 1 0 0]
 [0 0 1 0]
 [1 0 0 1]
 [0 0 0 0]]

R_1:
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 1. 0. 1.]
 [0. 0. 0. 0.]]

R_2:
[[0. 1. 1. 0.]
 [0. 0. 1. 0.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]]

R_3:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]]

R_4:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]]

Transitive Closure T: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]]


## Floyd-Warshall All Pair shortest path

In [11]:
def floyd_warshal_apsp(input_matrix):
    D_0 = input_matrix
    D_k_1 = D_0
    D_k = np.zeros(input_matrix.shape)
    N = input_matrix.shape[0]
    print(f'D\u2070:\n{D_0}')
    for k in range(N):
        for i in range(N):
            for j in range(N):
                D_k[i,j] = min(D_k_1[i,j] , (D_k_1[i,k] + D_k_1[k,j]))                
        print(f'\nD_{k+1}:\n{D_k}')
        D_k_1 = D_k
    print(f'\nShortest path Matrix: \n {D_k}')  

In [12]:
floyd_warshal_apsp(np.array([[0,np.inf,3,np.inf],[2,0,np.inf,np.inf],[np.inf,7,0,1],[6,np.inf,np.inf,0]]))

D⁰:
[[ 0. inf  3. inf]
 [ 2.  0. inf inf]
 [inf  7.  0.  1.]
 [ 6. inf inf  0.]]

D_1:
[[ 0. inf  3. inf]
 [ 2.  0.  5. inf]
 [inf  7.  0.  1.]
 [ 6. inf  9.  0.]]

D_2:
[[ 0. inf  3. inf]
 [ 2.  0.  5. inf]
 [ 9.  7.  0.  1.]
 [ 6. inf  9.  0.]]

D_3:
[[ 0. 10.  3.  4.]
 [ 2.  0.  5.  6.]
 [ 9.  7.  0.  1.]
 [ 6. 16.  9.  0.]]

D_4:
[[ 0. 10.  3.  4.]
 [ 2.  0.  5.  6.]
 [ 7.  7.  0.  1.]
 [ 6. 16.  9.  0.]]

Shortest path Matrix: 
 [[ 0. 10.  3.  4.]
 [ 2.  0.  5.  6.]
 [ 7.  7.  0.  1.]
 [ 6. 16.  9.  0.]]
