## Floyd-Warshall Transitive Closure

In [1]:
import numpy as np

In [28]:
def floyd_warshal(input_matrix):
    R_0 = input_matrix
    R_k_1 = R_0
    R_k = np.zeros(input_matrix.shape)
    N = input_matrix.shape[0]
    print(f'R\u2070:\n{R_0}')
    for k in range(N):
        for i in range(N):
            for j in range(N):
                R_k[i,j] = R_k_1[i,j].astype(bool) | (R_k_1[i,k].astype(bool) & R_k_1[k,j].astype(bool))
                R_k[i,j] = R_k[i,j].astype(int)
        print(f'\nR_{k+1}:\n{R_k}')
        R_k_1 = R_k
    print(f'\nTransitive Closure T: \n {R_k}')   
    

In [29]:
floyd_warshal(np.array([[0,1,0,0],[0,0,1,0],[1,0,0,1],[0,0,0,0]]))

R⁰:
[[0 1 0 0]
 [0 0 1 0]
 [1 0 0 1]
 [0 0 0 0]]

R_1:
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 1. 0. 1.]
 [0. 0. 0. 0.]]

R_2:
[[0. 1. 1. 0.]
 [0. 0. 1. 0.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]]

R_3:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]]

R_4:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]]

Transitive Closure T: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]]


In [11]:
bool(1).astype(int)

AttributeError: 'bool' object has no attribute 'astype'

In [13]:
a = np.array([1,1,0])

In [14]:
a

array([1, 1, 0])

In [17]:
a.astype(bool).astype(int)

array([1, 1, 0])

In [19]:
a.astype(bool) | a.astype(bool)

array([ True,  True, False])

In [21]:
a[1].astype(bool).astype(int)

1